name: BetaCraft
main: pl.betacraft.moresteck.Betacraft
version: 1.3.5-patch11
authors: [Moresteck, Kazu]
description: Zestaw autorskich pluginow na serwer BetaCraft 1.6.6-1.7.3
depend: [Essentials, Permissions]
softdepend: [MultiVerse]

commands:
    dzialka:
        usage: /dzialka
    bazar:
        usage: /bazar
    seed:
        usage: /seed
    save:
        usage: /save
    lb:
        usage: /lb
    rollback:
        usage: /rollback
    kup:
        usage: /kup
    sprzedaj:
        usage: /sprzedaj
    hban:
        usage: /hban
    hunban:
        usage: /hunban
    cobblex:
        usage: /cobblex
    cb:
        usage: /cb
    setblock:
        usage: /setblock
    itemy:
        usage: /itemy
    cp:
        usage: /cp
    cpreload:
        usage: /cpreload