name: BetaCraft
main: pl.betacraft.moresteck.Betacraft
version: 1.3.6c
authors: [Moresteck, Kazu]
description: Zestaw autorskich pluginow na serwer BetaCraft 1.7.3
depend: [Essentials, Permissions]
softdepend: [MultiVerse]

commands:
    dzialka:
        usage: /dzialka
    bazar:
        usage: /bazar
    seed:
        usage: /seed
    save:
        aliases: [bcsave]
        usage: /save
    lb:
        aliases: [logblock]
        usage: /lb
    rollback:
        usage: /rollback
    hban:
        usage: /hban
    hunban:
        usage: /hunban
    cobblex:
        usage: /cobblex
    cb:
        usage: /cb
    setblock:
        usage: /setblock
    itemy:
        usage: /itemy
    cp:
        usage: /cp
    cpreload:
        usage: /cpreload
    clearitems:
        usage: /clearitems
    adminchat:
        aliases: [ac]
        usage: /adminchat